<?php


/**
 * Class ContentElementDataObject
 */
class ContentElementDataObject extends DataExtension
{

//    public function updateCMSFields(FieldList $fields)
//    {
////        //var_dump($fields);die();
////        $fields->removeByName('action_doNew');
////        $fields->removeByName('doNew');
////        $fields->removeByName('add');
//        $fields->removeByName('BetterButton_New');
////        $fields->get
//        $fields->push( FormAction::create(
//            'bla', 'bla blub' )
//            ->addExtraClass('ss-ui-action-constructive')
//            ->setAttribute('data-icon', 'accept')
//        );
//        parent::updateCMSFields($fields); // TODO: Change the autogenerated stub
////        $fields->removeByName('action_doNew');
////        $fields->removeByName('doNew');
////        $fields->removeByName('add');
//        $fields->removeByName('BetterButton_New');
//
//        return $fields;
//    }

    /**
     * Updates the detail form to include new form actions and buttons
     *
     * @param Form The ItemEditForm object
     */
    public function updateItemEditForm($form) {
        //var_dump($form);die();
//        if ($this->owner->record->stat('better_buttons_enabled') !== true) {
//            return false;
//        }
//        Requirements::css(BETTER_BUTTONS_DIR.'/css/gridfield_betterbuttons.css');
//        Requirements::javascript(BETTER_BUTTONS_DIR.'/javascript/gridfield_betterbuttons.js');
//
//
//        $actions = $this->owner->record->getBetterButtonsActions();
//        $form->setActions($this->filterFieldList($form, $actions));
//
//        if($form->Fields()->hasTabset()) {
//            $form->Fields()->findOrMakeTab('Root')->setTemplate('TabSet');
//            $form->addExtraClass('cms-tabset');
//        }
//
//        $utils = $this->owner->record->getBetterButtonsUtils();
//        $form->Utils = $this->filterFieldList($form, $utils);
//        $form->setTemplate('BetterButtons_EditForm');
//        $form->addExtraClass('better-buttons-form');
    }

    public function updateCMSActions(FieldList $actions) {

        $actions->push(FormAction::create(
            'bla', 'bla blub' )
            ->addExtraClass('ss-ui-action-constructive')
            ->setAttribute('data-icon', 'accept')
        );

        $actions->removeByName('action_doNew');
        $actions->removeByName('doNew');
        $actions->removeByName('add');
        $actions->removeByName('BetterButton_New');
        $actions->removeByName('action_save');

        parent::updateCMSActions($actions);
        return $actions;
    }

}
